backend: 
    name: github
    repo: aliciavissuet/netlifyTest

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Image Alt Tag, name: imageAltTag, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: markdown}
          - {label: Outlined Button Text, name: outlinedButtonText, widget: string}
          - {label: Outlined Button Link, name: outlinedButtonLink, widget: string}
          - {label: Solid Button Text, name: solidButtonText, widget: string}
          - {label: Solid Button Link, name: solidButtonLink, widget: string}
          